app:
  api_key: changeme
  debug: true
  host: 0.0.0.0
  name: Sanl
  port: 8899
  version: 2.2.0
database:
  path: ./data/nodes.db
scheduler:
  auto_clean_days: 7
  check_cron: 0 * * * *
  check_mode: speed
  fetch_cron: 0 * * * *
  qualified_latency_ms: 200
sources:
  github:
    enabled: true
    proxies:
    - https://ghfast.top/
    refresh_interval: 3600
  static_json:
    enabled: true
    path: ./data/sources.json
  telegram:
    enabled: true
    refresh_interval: 7200
subs_check:
  binary_path: ./subs-check
  concurrent: 30
  config_path: ./config/subs-check.yaml
  listen_port: :8199
  min_speed: 256
  output_dir: ./output
  speed_concurrent: 10
  speed_test_url: https://github.com/AaronFeng753/Waifu2x-Extension-GUI/releases/download/v2.21.12/Waifu2x-Extension-GUI-v2.21.12-Portable.7z
  timeout: 8000
