alive-test-url: http://gstatic.com/generate_204
check-interval: 30
concurrent: 240
download-mb: 1
download-timeout: 6
filter: []
listen-port: :8199
media-check: false
media-concurrent: 20
min-speed: 128
node-prefix: ''
output-dir: ./output
print-progress: false
rename-node: true
save-method: local
source:
  subscriptions: []
  url-subscriptions: []
speed-concurrent: 100
speed-test-url: http://cachefly.cachefly.net/10mb.test
sub-urls:
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.txt
- https://raw.githubusercontent.com/mfuu/v2ray/master/v2ray
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/trojan.txt
- https://raw.githubusercontent.com/awesome-vpn/awesome-vpn/master/clash.yaml
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_Sub.txt
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vless.txt
- https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt
- https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
- https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt
- http://127.0.0.1:8899/sub/internal/manual
sub-urls-concurrent: 40
sub-urls-retry: 3
timeout: 2000
total-speed-limit: 0
