alive-test-url: http://gstatic.com/generate_204
check-interval: 30
concurrent: 120
download-mb: 1
download-timeout: 6
filter: []
listen-port: :8199
media-check: true
media-concurrent: 10
min-speed: 256
node-prefix: ''
output-dir: ./output
print-progress: false
rename-node: true
save-method: local
source:
  subscriptions: []
  url-subscriptions: []
speed-concurrent: 40
speed-test-url: http://cachefly.cachefly.net/10mb.test
sub-urls:
- https://raw.githubusercontent.com/zhuhaiuk/free-nodes/main/config.yaml
- https://raw.githubusercontent.com/zhuhaiuk/free-nodes/main/README.md
- https://raw.githubusercontent.com/Au1rxx/free-vpn-subscriptions/main/sub/mix
- https://raw.githubusercontent.com/Au1rxx/free-vpn-subscriptions/main/config.yaml
- https://raw.githubusercontent.com/Au1rxx/free-vpn-subscriptions/main/README.md
- https://raw.githubusercontent.com/zhuhaiuk/free-nodes/main/clash.yaml
- https://raw.githubusercontent.com/zhuhaiuk/free-nodes/main/clash.yml
- https://raw.githubusercontent.com/zhuhaiuk/free-nodes/main/sub/mix
- https://raw.githubusercontent.com/Au1rxx/free-vpn-subscriptions/main/clash.yaml
- https://raw.githubusercontent.com/Au1rxx/free-vpn-subscriptions/main/clash.yml
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_Sub.txt
- https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vless.txt
- https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt
- https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
- https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
- https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt
sub-urls-concurrent: 20
sub-urls-retry: 3
timeout: 2000
total-speed-limit: 0
