plugins {
    id 'com.android.application'
}

android {
    namespace 'io.sanl.app'
    compileSdk 34

    defaultConfig {
        applicationId "io.sanl.app"
        minSdk 24
        targetSdk 34
        versionCode 24200
        versionName "2.4.2"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'

    constraints {
        implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21') {
            because 'androidx dependencies need a consistent kotlin-stdlib version'
        }
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}
